// Author: reDragonCoder

// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms 
// will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do
// no exceed four million, find the sum of the even-valued terms.

#include <iostream>
using namespace std;

int main(){
    long long int lastNum=0, actualNum=1, tempNum=0, sum=0;
 
    while(actualNum<4000000){
        tempNum=lastNum+actualNum;

        if(tempNum%2==0){
            sum+=tempNum;
        }
        lastNum=actualNum;
        actualNum=tempNum;
    }

    cout<<sum;
    return 0;
}